### ISSUE TITLE
Locations become unobtainable

### ISSUE THREAD

**Issue by chandler05** [BrandenEK/AShortHike.Randomizer#20]
~~Compass Guy doesn't give you an item if the compass was obtained before talking to him.~~

**Comment by BrandenEK** [comment]
Locations unable to be completed because of already obtained items:
- [ ] Camper guy bribe
- [ ] Compass guy
- [ ] Get permit from fish

**Comment by chandler05** [comment]
- [ ] Taylor the Turtle Headband Gift
- [ ] Lose Race Gift

**Comment by BrandenEK** [comment]
Fisherman takes away fishing rod after catching all fish

**Comment by BrandenEK** [comment]
Outlook point dog sets TMap4 flag regardless of item
