### ISSUE TITLE
Allow Copy/Paste in Archipelago connection menu

### ISSUE THREAD

**Issue by chandler05** [BrandenEK/AShortHike.Randomizer#35]
Currently you must manually type the connection details, and it would save a lot of time to be able to copy and paste in the server details.

**Comment by BrandenEK** [comment]
Yep that would be great and shouldnt be too hard to do, will look into this soon

**Comment by BrandenEK** [comment]
Never mind, this is impossible.  The clipboard information is windows only, and also only possible in a windows forms app
